name: CustomStoneDrop
version: '1'
main: me.Cashtann.customStoneDrop.CustomStoneDrop
api-version: '1.20'

commands:
  customstonedrop:
    description: 'Reloads Custom Stone Drop plugin'
    permission: csd.admin
    aliases:
      - cstonedrop
  csdmenu:
    description: 'Opens Custom Stone Drop menu'
    permission: csd.admin
    aliases:
      - cstonedmenu
      - customstonedropsmenu
  itemglint:
    description: 'Adds enchanted glint (hides enchants!)'
    permission: csd.glint

permissions:
  csd.admin:
    description: 'Custom Stone Drop plugin - admin permission'
    default: op
  csd.drop:
    description: 'Allows to get a drop (if the drop is set)'
  csd.glint:
    description: 'Allows to apply glint to an item'
    default: op
